grafana:
  adminPassword: Dynamips64
  env:
    GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: "V6GTPn2EopIeVJxETmlyy6BwEnUCU3xW"

  grafana.ini:
    server:
      root_url: https://grafana.nj.test.lab

    auth:
      disable_login_form: false

    auth.generic_oauth:
      enabled: true
      name: keycloak
      allow_sign_up: true

      client_id: grafana
      client_secret: $_env{GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET}

      scopes: openid profile email

      auth_url: https://keycloak.nj.test.lab/realms/nj-test-lab/protocol/openid-connect/auth
      token_url: https://keycloak.nj.test.lab/realms/nj-test-lab/protocol/openid-connect/token
      api_url: https://keycloak.nj.test.lab/realms/nj-test-lab/protocol/openid-connect/userinfo

      role_attribute_path: contains(groups[*], 'grafana-admin') && 'Admin'|| 'Viewer'

      use_pkce: true

  ingress:
    enabled: false
    ingressClassName: nginx

    hosts:
      - grafana.nj.test.lab

    tls:
      - secretName: grafana-tls
        hosts:
          - grafana.nj.test.lab

  persistence:
    enabled: true
    storageClassName: rook-ceph-block
    size: 10Gi

prometheus:
  prometheusSpec:
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: rook-ceph-block
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 25Gi
